apiVersion: v1
kind: Service
metadata:
  name: jdp-consulting-website
  namespace: html
spec:
  selector:
    app: jdp-consulting-website
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: jdp-consulting-website
      protocol: TCP
      port: 80
      targetPort: 80
